create database PRED_MACHINE; 

create table Computadora(
IDCOMPUTADORA INT IDENTITY (1,1) NOT NULL,
NOMBRE NVARCHAR (50) NOT NULL,
DESCRIPCION NVARCHAR (80) NOT NULL,
PRECIO DECIMAL NOT NULL,
FECHAFABRIC DATETIME NOT NULL
);